Repository serenity-rs/songbird, pull requests merged in 2020-11, with the labels that each got.

#1 Offer youtube-dlc as an alternative to youtube-dl
  Cargo.toml
  src/input/ytdl_src.rs
Labels: enhancement

#2 Add a dependencies section in the README
  README.md
Labels: documentation, enhancement

#7 Track queue extension
  Cargo.toml
  examples/serenity/voice_events_queue/Cargo.toml
  examples/serenity/voice_events_queue/src/main.rs
  src/driver/mod.rs
  src/tracks/handle.rs
  src/tracks/mod.rs
  src/tracks/queue.rs
Labels: enhancement

#8 fix clippy warning
  src/input/mod.rs
Labels: enhancement

#15 Input: Make restartable sources fully async
  examples/twilight/src/main.rs
  src/input/restartable.rs
Labels: breaking, fix, input

#16 Add function to return a vector of all the handles in a queue
  src/tracks/queue.rs
Labels: enhancement, tracks

#18 Fixed serenity dependency default features
  Cargo.toml
Labels: fix

#19 Move to new intra-doc links, make events non-exhaustive.
  src/driver/config.rs
  src/driver/decode_mode.rs
  src/driver/mod.rs
  src/error.rs
  src/events/context.rs
  src/events/core.rs
  src/events/data.rs
  src/events/mod.rs
  src/events/store.rs
  src/events/track.rs
  src/events/untimed.rs
  src/handler.rs
  src/input/cached/compressed.rs
  src/input/cached/memory.rs
  src/input/codec/mod.rs
  src/input/codec/opus.rs
  src/input/error.rs
  src/input/ffmpeg_src.rs
  src/input/metadata.rs
  src/input/mod.rs
  src/input/reader.rs
  src/input/restartable.rs
  src/lib.rs
  src/manager.rs
  src/serenity.rs
  src/tracks/command.rs
  src/tracks/handle.rs
  src/tracks/looping.rs
  src/tracks/mod.rs
  src/tracks/mode.rs
  src/tracks/queue.rs
  src/tracks/state.rs
Labels: documentation, enhancement, events
