Repository serenity-rs/songbird, pull requests merged in 2021-03, with the labels that each got.

#44 Break reference cycle in voice storage example
  examples/serenity/voice_storage/src/main.rs
Labels: example, fix

#45 Fix input source timestamp pre-input argument decimal formatting
  src/input/restartable.rs
Labels: fix, input

#46 Prevent mixer thread from waking while inactive
  src/driver/tasks/mixer.rs
  src/manager.rs
Labels: driver, fix

#43 Organise and document processes and architecture
  ARCHITECTURE.md
  CONTRIBUTING.md
  Makefile.toml
  README.md
  images/arch.afdesign
  images/driver.png
  images/driver.svg
  images/gateway.png
  images/gateway.svg
Labels: documentation, enhancement

#49 Gateway: Allow connection info to be retrieved
  src/handler.rs
  src/info.rs
Labels: enhancement, gateway

#50 Deps: Update async-tungstenite -> 0.13
  Cargo.toml
Labels: enhancement

#47 Gateway: Fix repeat joins on same channel from stalling
  src/handler.rs
  src/info.rs
  src/manager.rs
Labels: breaking, fix, gateway

#52 Deps: Bump DiscoRTP version -> 0.3
  Cargo.toml
Labels: breaking, driver, enhancement, events

#51 Gateway: Add connection timeout, add `Config` to gateway.
  ARCHITECTURE.md
  Cargo.toml
  Makefile.toml
  examples/serenity/voice_receive/src/main.rs
  src/config.rs
  src/driver/mod.rs
  src/driver/tasks/error.rs
  src/driver/tasks/mixer.rs
  src/driver/tasks/mod.rs
  src/driver/tasks/udp_rx.rs
  src/error.rs
  src/handler.rs
  src/input/cached/tests.rs
  src/input/mod.rs
  src/join.rs
  src/lib.rs
  src/manager.rs
  src/serenity.rs
Labels: breaking, enhancement, gateway
